### PR TITLE
Fix: URL params & error msg

### LINKED ISSUE #93: Hovercard assumes profile URL has no query parameters
The hovercard assumes the profile URL has no query parameters and it then adds a `?utm_source=hovercard` to all profile URLs. If the profile URL already has query parameters then this leads to a double `?`.

Ideally we check for existing parameters and use `?` or `&` appropriately.

```js
const trackedProfileUrl = escUrl( `${ profileUrl }?utm_source=hovercard` );
```

### LINKED ISSUE #101: Hovercards: Add `404` error message
We have a new `404` error response from the REST API. We can add it to the hovercards library.

- Message: `Profile not found.`

### PR DESCRIPTION
**Pull request by wellyshen**
- Related to #101
- Related to #93

## Proposed Changes

* Create an `addQueryArg` utility function to fix the issue
* Add a 404 error msg

## Testing Instructions

* Check out this PR
* Follow [the development guidance](https://github.com/Automattic/gravatar/blob/trunk/docs/CONTRIBUTING.md#development-workflow) to run the PR
* Check the requested API URL, and the URL param still works the same:

截圖 2024-10-28 晚上8 27 45

* Check the "View Profile" link, and the URL param still works the same:

截圖 2024-10-28 晚上8 28 05

* For the error msg, code review should be enough

### CODE REVIEW

File: web/packages/hovercards/src/add-query-arg.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+ * @return {string}      - The updated URL with the new or updated query parameter, or an empty string if the URL is invalid.
+ */
+export default function addQueryArg( url: string, key: string, value: string ): string {
+	const [ baseUrl, queryStr ] = url.split( '?' );
+	const queryParams = new URLSearchParams( queryStr || '' );
+
+	queryParams.set( key, value );
+
+	return `${ baseUrl }?${ queryParams.toString() }`;
+}
```
Comment (wellyshen) [inline web/packages/hovercards/src/add-query-arg.ts:16]: Although I'm not happy with the [increased library size](https://github.com/Automattic/gravatar/pull/119#issuecomment-2441468076), I think it's an acceptable compromise between size ([we've reduced the size already](https://github.com/Automattic/gravatar/pull/119/commits/7ee58980ee8adabe66338a4ee928023a88f86140)) and reliability.

**Review by jcheringer — APPROVED** [review]
